spring.application.name=concurdev-backend

spring.datasource.url=jdbc:mysql://localhost:3306/flowboard_db
spring.datasource.username=root
spring.datasource.password=Ba1man@joker

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080